SELECT [trans_no]
      ,[seq_no]
      ,[store_no]
      ,[organization_no]
      ,[tendertype]
      ,[amount]
      ,[change_amt]
      ,[tender_desc]
      ,[change_desc]
      ,[locale_language]
      ,[locale_country]
      ,[data_capture]
      ,[state]
  FROM [possite].[dbo].[trans_tender]