SELECT [trans_no]
      ,[store_no]
      ,[organization_no]
      ,[pos_no]
      ,[drawer_no]
      ,[config_no]
      ,[trans_type]
      ,[state]
      ,[reason_code]
      ,[customer_no]
      ,[start_time]
      ,[complete_time]
      ,[emp_no]
      ,[carry_out]
      ,[training_mode]
      ,[table_name]
      ,[archive_date]
      ,[upload_date]
      ,[replication_date]
  FROM [possite].[dbo].[trans]